import React, { useEffect, useState } from 'react';
import { Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { ArrowUpRight, Bell, CalendarCheck2, CarFront, CircleCheck, Clock3, CreditCard, History as HistoryIcon, LayoutDashboard, LogOut, MapPin, ParkingCircle, Search, ShieldCheck, UserRound } from 'lucide-react';
import api from './api/client';
import { useAuth } from './context/AuthContext';

const nav = [{ to: '/dashboard', label: 'Dashboard' }, { to: '/vehicles', label: 'My Vehicles' }, { to: '/slots', label: 'Find a Slot' }, { to: '/bookings', label: 'My Bookings' }, { to: '/history', label: 'Parking History' }, { to: '/payments', label: 'Payments' }, { to: '/profile', label: 'Profile' }];
const adminNav = [{ to: '/admin', label: 'Admin Overview' }, { to: '/admin/slots', label: 'Manage Slots' }, { to: '/admin/users', label: 'Users' }, { to: '/admin/operations', label: 'Operations' }];
function Spinner() { return <div className="spinner" aria-label="Loading" /> }
function Toast({ toast }) { return toast && <div className={`toast ${toast.type || 'success'}`}>{toast.message}</div> }
function Protected({ children, admin = false }) { const { user, loading } = useAuth(); if (loading) return <div className="center"><Spinner /></div>; if (!user) return <Navigate to="/login" replace />; if (admin && user.role !== 'ADMIN') return <Navigate to="/dashboard" replace />; return children }
function Layout({ children, toast, setToast }) { const { user, logout } = useAuth(); const go = useNavigate(); const links = user.role === 'ADMIN' ? [...nav, ...adminNav] : nav; const icons = { '/dashboard': LayoutDashboard, '/vehicles': CarFront, '/slots': Search, '/bookings': CalendarCheck2, '/history': HistoryIcon, '/payments': CreditCard, '/profile': UserRound, '/admin': ShieldCheck, '/admin/slots': ParkingCircle, '/admin/users': UserRound, '/admin/operations': Clock3 }; return <div className="shell"><aside className="sidebar"><div className="brand">Park<span>Smart</span></div><p className="role">{user.role === 'ADMIN' ? 'Administrator' : 'Driver portal'}</p><nav>{links.map(x => { const Icon = icons[x.to]; return <NavLink key={x.to} to={x.to}>{Icon && <Icon size={18} strokeWidth={2} />}<span className="nav-label">{x.label}</span></NavLink> })}</nav><button className="logout" onClick={() => { logout(); go('/'); }}><LogOut size={18} /><span className="nav-label">Sign out</span></button></aside><section className="content"><header className="navbar"><div><strong>Smart Parking</strong><small>Safe, simple, connected</small></div><button className="dashboard-alert" aria-label="Notifications"><Bell size={19} /></button><div className="avatar">{user.name?.[0]?.toUpperCase()}</div></header>{children}<Toast toast={toast} /></section></div> }
function Landing() { const go = useNavigate(); return <main className="landing"><nav><div className="brand">Park<span>Smart</span></div><div><button className="linkbtn" onClick={() => go('/login')}>Sign in</button><button onClick={() => go('/register')}>Get started</button></div></nav><section className="hero"><div><p className="eyebrow">PARK WITH CONFIDENCE</p><h1>Your parking space, <em>already waiting.</em></h1><p className="lead">Find a suitable space, reserve it in seconds, and manage every parking visit from one clean dashboard.</p><button onClick={() => go('/register')}>Reserve a space →</button></div><div className="hero-card"><div className="pin">P</div><h3>Live availability</h3><p>See which spaces are free right now.</p><div className="mini-slots"><i /><i /><i className="busy" /><i /></div></div></section><section className="feature-row">{[['Reserve', 'Automatic compatible slot allocation'], ['Track', 'Complete booking and parking history'], ['Pay', 'Cash, UPI, or card receipt records']].map(([a, b]) => <article key={a}><h3>{a}</h3><p>{b}</p></article>)}</section></main> }
function AuthPage({ register }) { const { save } = useAuth(); const go = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '', phone: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { const { data } = await api.post(register ? '/auth/register' : '/auth/login', register ? form : { email: form.email, password: form.password }); save(data); go('/dashboard') } catch (e) { setError(e.response?.data?.message || 'Unable to continue.') } finally { setBusy(false) } }; return <main className="auth-page"><div className="auth-panel"><div className="brand">Park<span>Smart</span></div><h1>{register ? 'Create your account' : 'Welcome back'}</h1><p>{register ? 'Start managing your parking in minutes.' : 'Sign in to manage your parking.'}</p><form onSubmit={submit}>{register && <Field label="Full name" value={form.name} onChange={v => setForm({ ...form, name: v })} />}<Field label="Email address" type="email" value={form.email} onChange={v => setForm({ ...form, email: v })} /><Field label="Password" type="password" value={form.password} onChange={v => setForm({ ...form, password: v })} />{register && <Field label="Phone (optional)" value={form.phone} onChange={v => setForm({ ...form, phone: v })} />} {error && <p className="form-error">{error}</p>}<button disabled={busy} className="wide">{busy ? <Spinner /> : register ? 'Create account' : 'Sign in'}</button></form><p className="switch">{register ? 'Already registered?' : 'New here?'} <a onClick={() => go(register ? '/login' : '/register')}>{register ? 'Sign in' : 'Create an account'}</a></p></div></main> }
function Field({ label, type = 'text', value, onChange, required = true }) { return <label>{label}<input type={type} value={value || ''} required={required} onChange={e => onChange(e.target.value)} /></label> }
function Page({ title, children, action }) { return <main className="app-page"><div className="page-title"><div><p className="page-eyebrow">PARKSMART WORKSPACE</p><h1>{title}</h1></div>{action}</div>{children}</main> }
function Dashboard() { const { user } = useAuth(); const go = useNavigate(); const [bookings, setBookings] = useState([]); const [slots, setSlots] = useState([]); const activeBookings = bookings.filter(b => b.booking_status === 'BOOKED').length; const completedVisits = bookings.filter(b => b.booking_status === 'COMPLETED').length; useEffect(() => { Promise.all([api.get('/bookings'), api.get('/slots?status=AVAILABLE')]).then(([b, s]) => { setBookings(b.data.bookings); setSlots(s.data.slots) }).catch(() => { }) }, []); return <main className="dashboard"><section className="dashboard-hero"><div><p className="dashboard-kicker"><span /> YOUR PARKING OVERVIEW</p><h1>Good to see you, {user.name.split(' ')[0]}.</h1><p>Everything you need for a smoother parking day, all in one place.</p></div><button className="dashboard-cta" onClick={() => go('/slots')}>Find a space <ArrowUpRight size={18} /></button></section><section className="dashboard-stats"><DashboardStat icon={<MapPin />} label="Available spaces" value={slots.length} detail="Ready to reserve now" tone="blue" /><DashboardStat icon={<CalendarCheck2 />} label="Active bookings" value={activeBookings} detail={activeBookings ? 'Your spaces are reserved' : 'No active reservations'} tone="violet" /><DashboardStat icon={<CircleCheck />} label="Completed visits" value={completedVisits} detail="Total parking sessions" tone="green" /></section><section className="dashboard-main"><div className="dashboard-table-card"><div className="dashboard-card-heading"><div><p className="dashboard-card-eyebrow">ACTIVITY</p><h2>Recent bookings</h2><p>Keep track of your latest parking activity.</p></div><button className="dashboard-link" onClick={() => go('/bookings')}>View all <ArrowUpRight size={16} /></button></div><BookingsTable rows={bookings.slice(0, 5)} /></div><aside className="dashboard-availability"><div className="availability-icon"><ParkingCircle size={22} /></div><p className="dashboard-card-eyebrow">LIVE AVAILABILITY</p><h2>Spaces are open nearby</h2><p>There are <strong>{slots.length} spaces</strong> currently available to reserve.</p><div className="availability-meter"><span style={{ width: `${Math.min(100, slots.length * 10)}%` }} /></div><div className="availability-meta"><span><i /> Live updates</span><span>{slots.length} open</span></div><button className="availability-button" onClick={() => go('/slots')}>Explore spaces <ArrowUpRight size={16} /></button></aside></section></main> }
function DashboardStat({ icon, label, value, detail, tone }) { return <article className={`dashboard-stat ${tone}`}><div className="dashboard-stat-icon">{icon}</div><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article> }
function Stat({ label, value }) { return <article className="stat"><small>{label}</small><strong>{value}</strong></article> }
function Vehicles({ toast }) { const [vehicles, setVehicles] = useState([]); const [form, setForm] = useState({ vehicle_number: '', vehicle_type: 'CAR', owner_name: '' }); const [edit, setEdit] = useState(null); const load = () => api.get('/vehicles').then(r => setVehicles(r.data.vehicles)); useEffect(() => { void load(); }, []); const save = async e => { e.preventDefault(); try { if (edit) await api.put(`/vehicles/${edit}`, form); else await api.post('/vehicles', form); setForm({ vehicle_number: '', vehicle_type: 'CAR', owner_name: '' }); setEdit(null); load(); toast('Vehicle saved.') } catch (e) { toast(e.response?.data?.message || 'Could not save vehicle.', 'error') } }; return <Page title="My Vehicles"><div className="two-col"><section className="panel"><h2>{edit ? 'Edit vehicle' : 'Add vehicle'}</h2><form onSubmit={save}><Field label="Vehicle number" value={form.vehicle_number} onChange={v => setForm({ ...form, vehicle_number: v })} /><label>Type<select value={form.vehicle_type} onChange={e => setForm({ ...form, vehicle_type: e.target.value })}><option>CAR</option><option>BIKE</option></select></label><Field label="Owner name" value={form.owner_name} onChange={v => setForm({ ...form, owner_name: v })} /><button>{edit ? 'Update vehicle' : 'Add vehicle'}</button></form></section><section className="panel"><h2>Registered vehicles</h2><table><thead><tr><th>Number</th><th>Type</th><th /></tr></thead><tbody>{vehicles.map(v => <tr key={v.id}><td>{v.vehicle_number}</td><td>{v.vehicle_type}</td><td><button className="text" onClick={() => { setEdit(v.id); setForm(v) }}>Edit</button><button className="text danger" onClick={async () => { await api.delete(`/vehicles/${v.id}`); load(); toast('Vehicle removed.') }}>Delete</button></td></tr>)}</tbody></table></section></div></Page> }
function Slots({ toast }) { const [slots, setSlots] = useState([]), [vehicles, setVehicles] = useState([]), [type, setType] = useState(''), [search, setSearch] = useState(''), [vehicleId, setVehicleId] = useState(''); const load = () => api.get(`/slots?status=AVAILABLE&type=${type}&search=${search}`).then(r => setSlots(r.data.slots)); useEffect(() => { load(); api.get('/vehicles').then(r => setVehicles(r.data.vehicles)) }, [type, search]); const book = async slot => { if (!vehicleId) return toast('Select a vehicle first.', 'error'); try { await api.post('/bookings', { vehicleId: Number(vehicleId), slotType: slot.slot_type }); toast(`Slot ${slot.slot_number} booked.`); load() } catch (e) { toast(e.response?.data?.message || 'Booking failed.', 'error') } }; return <Page title="Find a parking space"><section className="panel filters"><select value={type} onChange={e => setType(e.target.value)}><option value="">All types</option><option>CAR</option><option>BIKE</option><option>EV</option><option>HANDICAP</option></select><input placeholder="Search slot or zone" value={search} onChange={e => setSearch(e.target.value)} /><select value={vehicleId} onChange={e => setVehicleId(e.target.value)}><option value="">Choose your vehicle</option>{vehicles.map(v => <option key={v.id} value={v.id}>{v.vehicle_number} ({v.vehicle_type})</option>)}</select></section><div className="slot-grid">{slots.map(s => <article className="slot" key={s.id}><b>{s.slot_number}</b><span>{s.slot_type}</span><small>Zone {s.zone} · Level {s.level_number}</small><button onClick={() => book(s)}>Book</button></article>)}</div>{!slots.length && <Empty text="No available spaces match your filters." />}</Page> }
function Bookings({ toast }) {
  const [rows, setRows] = useState([]);
  const load = () => api.get('/bookings').then(r => setRows(r.data.bookings));

  useEffect(() => {
    void load();
  }, []);

  return (
    <Page title="My Bookings">
      <section className="panel">
        <BookingsTable
          rows={rows}
          actions={b =>
            b.booking_status === 'BOOKED' &&
            <button
              className="text danger"
              onClick={async () => {
                await api.patch(`/bookings/${b.id}/cancel`);
                load();
                toast('Booking cancelled.');
              }}
            >
              Cancel
            </button>
          }
        />
      </section>
    </Page>
  );
}
function BookingsTable({ rows, actions }) { return <table><thead><tr><th>Booking</th><th>Vehicle</th><th>Slot</th><th>Status</th><th /></tr></thead><tbody>{rows.length ? rows.map(b => <tr key={b.id}><td>{b.booking_code || `#${b.id}`}</td><td>{b.vehicle_number}</td><td>{b.slot_number}</td><td><span className={`badge ${b.booking_status?.toLowerCase()}`}>{b.booking_status}</span></td><td>{actions?.(b)}</td></tr>) : <tr><td colSpan="5">No bookings found.</td></tr>}</tbody></table> }
function History() { const [history, setHistory] = useState([]); useEffect(() => { api.get('/bookings/history').then(r => setHistory(r.data.history)) }, []); return <Page title="Parking History"><section className="panel"><table><thead><tr><th>Vehicle</th><th>Slot</th><th>Entry</th><th>Exit</th><th>Fee</th></tr></thead><tbody>{history.map(h => <tr key={h.id}><td>{h.vehicle_number}</td><td>{h.slot_number}</td><td>{new Date(h.entry_time).toLocaleString()}</td><td>{h.exit_time ? new Date(h.exit_time).toLocaleString() : 'Active'}</td><td>₹{h.total_fee}</td></tr>)}</tbody></table></section></Page> }
function Payments({ toast }) { const [payments, setPayments] = useState([]); const load = () => api.get('/payments').then(r => setPayments(r.data.payments)); useEffect(() => { void load(); }, []); return <Page title="Payments & Receipts"><section className="panel"><table><thead><tr><th>Receipt</th><th>Vehicle</th><th>Amount</th><th>Method</th><th>Status</th><th /></tr></thead><tbody>{payments.map(p => <tr key={p.id}><td>{p.receipt_number}</td><td>{p.vehicle_number}</td><td>₹{p.amount}</td><td>{p.payment_method || '—'}</td><td>{p.payment_status}</td><td>{p.payment_status === 'PENDING' && <select defaultValue="" onChange={async e => { if (e.target.value) { await api.patch(`/payments/${p.booking_id}/pay`, { paymentMethod: e.target.value }); load(); toast('Payment completed.') } }}><option value="">Pay now</option><option>CASH</option><option>UPI</option><option>CARD</option></select>}</td></tr>)}</tbody></table></section></Page> }
function Profile({ toast }) { const { user, setUser } = useAuth(); const [form, setForm] = useState({ name: user.name, phone: user.phone || '' }); const [password, setPassword] = useState({ currentPassword: '', newPassword: '' }); return <Page title="My Profile"><div className="two-col"><section className="panel"><h2>Personal details</h2><form onSubmit={async e => { e.preventDefault(); try { const { data } = await api.put('/users/profile', form); setUser(data.user); localStorage.setItem('parking_user', JSON.stringify(data.user)); toast('Profile updated.') } catch (e) { toast('Could not update profile.', 'error') } }}><Field label="Name" value={form.name} onChange={v => setForm({ ...form, name: v })} /><Field label="Email" value={user.email} required={false} onChange={() => { }} /><Field label="Phone" value={form.phone} required={false} onChange={v => setForm({ ...form, phone: v })} /><button>Save profile</button></form></section><section className="panel"><h2>Change password</h2><form onSubmit={async e => { e.preventDefault(); try { await api.put('/users/password', password); setPassword({ currentPassword: '', newPassword: '' }); toast('Password changed.') } catch (e) { toast(e.response?.data?.message || 'Could not change password.', 'error') } }}><Field label="Current password" type="password" value={password.currentPassword} onChange={v => setPassword({ ...password, currentPassword: v })} /><Field label="New password" type="password" value={password.newPassword} onChange={v => setPassword({ ...password, newPassword: v })} /><button>Update password</button></form></section></div></Page> }
function AdminHome() { const [data, setData] = useState(null); useEffect(() => { api.get('/admin/dashboard').then(r => setData(r.data)) }, []); if (!data) return <Spinner />; return <Page title="Admin Dashboard"><div className="cards"><Stat label="Registered users" value={data.statistics.users} /><Stat label="Parking slots" value={data.statistics.slots} /><Stat label="Active bookings" value={data.statistics.activeBookings} /><Stat label="Revenue" value={`₹${data.statistics.revenue}`} /></div><section className="panel"><h2>Live occupancy</h2><div className="chart">{data.occupancy.map(x => <div key={x.status} style={{ height: `${Math.max(18, x.count * 28)}px` }}><span>{x.count}</span><small>{x.status}</small></div>)}</div></section></Page> }
function AdminSlots({ toast }) { const [slots, setSlots] = useState([]); const [form, setForm] = useState({ slot_number: '', slot_type: 'CAR', status: 'AVAILABLE', zone: 'A', level_number: 1 }); const [edit, setEdit] = useState(null); const load = () => api.get('/slots').then(r => setSlots(r.data.slots)); useEffect(() => { void load(); }, []); const save = async e => { e.preventDefault(); try { if (edit) await api.put(`/slots/${edit}`, form); else await api.post('/slots', form); setForm({ slot_number: '', slot_type: 'CAR', status: 'AVAILABLE', zone: 'A', level_number: 1 }); setEdit(null); load(); toast('Slot saved.') } catch (e) { toast(e.response?.data?.message || 'Could not save slot.', 'error') } }; return <Page title="Manage Parking Slots"><div className="two-col"><section className="panel"><h2>{edit ? 'Edit slot' : 'New slot'}</h2><form onSubmit={save}><Field label="Slot number" value={form.slot_number} onChange={v => setForm({ ...form, slot_number: v })} /><label>Type<select value={form.slot_type} onChange={e => setForm({ ...form, slot_type: e.target.value })}>{['CAR', 'BIKE', 'EV', 'HANDICAP'].map(x => <option key={x}>{x}</option>)}</select></label><label>Status<select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}>{['AVAILABLE', 'OCCUPIED', 'MAINTENANCE'].map(x => <option key={x}>{x}</option>)}</select></label><Field label="Zone" value={form.zone} onChange={v => setForm({ ...form, zone: v })} /><Field label="Level" type="number" value={form.level_number} onChange={v => setForm({ ...form, level_number: Number(v) })} /><button>Save slot</button></form></section><section className="panel"><table><thead><tr><th>Slot</th><th>Type</th><th>Status</th><th /></tr></thead><tbody>{slots.map(s => <tr key={s.id}><td>{s.slot_number}</td><td>{s.slot_type}</td><td>{s.status}</td><td><button className="text" onClick={() => { setEdit(s.id); setForm(s) }}>Edit</button><button className="text danger" onClick={async () => { await api.delete(`/slots/${s.id}`); load(); toast('Slot deleted.') }}>Delete</button></td></tr>)}</tbody></table></section></div></Page> }
function AdminUsers() { const [users, setUsers] = useState([]); useEffect(() => { api.get('/admin/users').then(r => setUsers(r.data.users)) }, []); return <Page title="Manage Users"><section className="panel"><table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Role</th></tr></thead><tbody>{users.map(u => <tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.phone || '—'}</td><td>{u.role}</td></tr>)}</tbody></table></section></Page> }
function AdminOperations({ toast }) { const [bookings, setBookings] = useState([]), [payments, setPayments] = useState([]); const load = () => Promise.all([api.get('/bookings?all=true'), api.get('/payments')]).then(([b, p]) => { setBookings(b.data.bookings); setPayments(p.data.payments) }); useEffect(() => { void load(); }, []); return <Page title="Bookings & Payments"><section className="panel"><h2>Active operations</h2><table><thead><tr><th>Booking</th><th>Vehicle</th><th>Slot</th><th>Action</th></tr></thead><tbody>{bookings.filter(b => b.booking_status === 'BOOKED').map(b => <tr key={b.id}><td>{b.booking_code}</td><td>{b.vehicle_number}</td><td>{b.slot_number}</td><td><button onClick={async () => { try { await api.post('/sessions/entry', { bookingId: b.id }); toast('Entry recorded.'); load() } catch (e) { if (e.response?.status === 409) { const h = await api.get('/bookings/history?all=true'); const active = h.data.history.find(x => x.booking_id === b.id && !x.exit_time); if (active) { await api.patch(`/sessions/${active.id}/exit`); toast('Exit recorded.'); load() } } else toast(e.response?.data?.message || 'Operation failed.', 'error') } }}>Entry / Exit</button></td></tr>)}</tbody></table></section><section className="panel"><h2>Payments</h2><table><thead><tr><th>Receipt</th><th>Vehicle</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{payments.map(p => <tr key={p.id}><td>{p.receipt_number}</td><td>{p.vehicle_number}</td><td>₹{p.amount}</td><td>{p.payment_status}</td><td>{p.payment_status === 'PENDING' && <select defaultValue="" onChange={async e => { if (e.target.value) { await api.patch(`/payments/${p.booking_id}/pay`, { paymentMethod: e.target.value }); load(); toast('Payment recorded.') } }}><option value="">Collect payment</option><option>CASH</option><option>UPI</option><option>CARD</option></select>}</td></tr>)}</tbody></table></section></Page> }
function Empty({ text }) { return <section className="panel empty">{text}</section> }
function App() { const [toast, setToast] = useState(null); const push = (message, type = 'success') => { setToast({ message, type }); setTimeout(() => setToast(null), 3500) }; const wrap = child => <Protected><Layout toast={toast} setToast={setToast}>{child}</Layout></Protected>; return <Routes><Route path="/" element={<Landing />} /><Route path="/login" element={<AuthPage />} /><Route path="/register" element={<AuthPage register />} /><Route path="/dashboard" element={wrap(<Dashboard />)} /><Route path="/vehicles" element={wrap(<Vehicles toast={push} />)} /><Route path="/slots" element={wrap(<Slots toast={push} />)} /><Route path="/bookings" element={wrap(<Bookings toast={push} />)} /><Route path="/history" element={wrap(<History />)} /><Route path="/payments" element={wrap(<Payments toast={push} />)} /><Route path="/profile" element={wrap(<Profile toast={push} />)} /><Route path="/admin" element={<Protected admin><Layout toast={toast}><AdminHome /></Layout></Protected>} /><Route path="/admin/slots" element={<Protected admin><Layout toast={toast}><AdminSlots toast={push} /></Layout></Protected>} /><Route path="/admin/users" element={<Protected admin><Layout toast={toast}><AdminUsers /></Layout></Protected>} /><Route path="/admin/operations" element={<Protected admin><Layout toast={toast}><AdminOperations toast={push} /></Layout></Protected>} /><Route path="*" element={<main className="not-found"><h1>404</h1><p>This parking space does not exist.</p><a href="/">Return home</a></main>} /></Routes> }
export default App;
